/// 2022 Systopia Lab, Computer Science, University of British Columbia. All rights reserved.


// OSSPEC Definitions for `MyOs`

// THIS FILE IS AUTOGENERATED BY THE VELOSIRAPTOR COMPILER



#ifndef MYOS_OSSPEC_H_
#define MYOS_OSSPEC_H_ 1


#include "types.h"

extern paddr_t pt_memory_alloc(size_t sz, paddr_t align, UnitType level);

extern void pt_memory_free(paddr_t pa, size_t sz, UnitType level);

extern vaddr_t local_phys_to_mem(paddr_t pa);

extern paddr_t mem_to_local_phys(vaddr_t va);

#endif // MYOS_OSSPEC_H_
